services:
  vazaar-postgres:
    image: postgres:17
    container_name: vazaar-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_vazaar_data:/var/lib/postgresql/data
    restart: always
    networks:
      - vazaar-default

  vazaar-web:
    build: .
    container_name: vazaar-web
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ata_shakeri@yahoo.com
    env_file:
      - .env
    depends_on:
      - vazaar-postgres
    volumes:
      - static_vazaar:/app/staticfiles
      - media_vazaar:/app/media
    networks:
      - vazaar-default
      - proxy

volumes:
  postgres_vazaar_data:
  static_vazaar:
  media_vazaar:

networks:
  proxy:
    external: true
    name: nginx-proxy
  vazaar-default:
    driver: bridge
