# Generated by Django 5.2.1 on 2025-07-06 17:21

import ckeditor_uploader.fields
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="نام برند")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع محصول",
                "verbose_name_plural": "انواع محصولات",
            },
        ),
        migrations.CreateModel(
            name="SpecialList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
            ],
            options={
                "verbose_name": "لیست ویژه",
                "verbose_name_plural": "لیست های ویژه",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "current_price",
                    models.BigIntegerField(default=0, verbose_name="قیمت فعلی"),
                ),
                (
                    "discount",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "old_price",
                    models.BigIntegerField(default=0, verbose_name="قیمت قبلی"),
                ),
                ("inventory", models.IntegerField(default=0, verbose_name="موجودی")),
                (
                    "short_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات کوتاه"
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات "
                    ),
                ),
                (
                    "primary_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس اصلی",
                    ),
                ),
                (
                    "secondary_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس اصلی",
                    ),
                ),
                (
                    "image_tag",
                    models.TextField(blank=True, null=True, verbose_name="برچسب عکس"),
                ),
                (
                    "offer_start_date",
                    models.DateField(auto_now=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "offer_end_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ انقضا",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="نوع ",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس بندانگشتی",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری محصول",
                "verbose_name_plural": "گالری محصولات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CountDownBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "image_left",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس چپ",
                    ),
                ),
                (
                    "image_right",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس راست",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "start_date",
                    models.DateField(auto_now=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ شمارش معکوس",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countdown_banners",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر شمارش معکوس",
                "verbose_name_plural": "بنرهای شمارش معکوس",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "small_title",
                    models.CharField(
                        default="title", max_length=100, verbose_name="عنوان ریز"
                    ),
                ),
                (
                    "big_title",
                    models.CharField(
                        default="title", max_length=100, verbose_name="عنوان درشت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
            },
        ),
        migrations.CreateModel(
            name="AboutProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("RTL", "سمت راست"), ("LTR", "سمت چپ")],
                        default="RTL",
                        max_length=3,
                        verbose_name="جای متن در صفحه",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره محصول",
                "verbose_name_plural": "درباره محصولات",
            },
        ),
        migrations.CreateModel(
            name="AboutAfterBeforeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "image_before",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس قبل",
                    ),
                ),
                (
                    "image_after",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="عکس بعد",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_after_before",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "قبل و بعد از محصول",
                "verbose_name_plural": "قبل و بعد از محصول",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="سوال")),
                ("answer", models.TextField(verbose_name="جواب")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال و جواب",
                "verbose_name_plural": "سوالات و جواب ها",
            },
        ),
        migrations.CreateModel(
            name="SpecialListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_list_items",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "special_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="product.speciallist",
                        verbose_name="لیست ویژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم لیست ویژه",
                "verbose_name_plural": "آیتم های لیست ویژه",
                "ordering": ["order"],
            },
        ),
    ]
