# Generated by Django 5.2.1 on 2025-07-17 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_specification_productspecificationvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecificationvalue",
            options={
                "ordering": ["order"],
                "verbose_name": " خصوصیت محصول",
                "verbose_name_plural": " خصوصیات محصولات",
            },
        ),
        migrations.AlterModelOptions(
            name="specification",
            options={
                "ordering": ["category__title", "name"],
                "verbose_name": "خصوصیت",
                "verbose_name_plural": "خصوصیات",
            },
        ),
        migrations.CreateModel(
            name="ProductVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس آی پی"
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="اطلاعات دستگاه",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان بازدید"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کابر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید محصول",
                "verbose_name_plural": "بازدیدهای محصولات",
                "ordering": ["-visited_at"],
            },
        ),
    ]
