# Generated by Django 5.2.1 on 2025-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_productspecificationvalue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="order",
            field=models.IntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
    ]
