# Generated by Django 5.2.1 on 2025-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_specification_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecificationvalue",
            options={
                "verbose_name": " خصوصیت محصول",
                "verbose_name_plural": " خصوصیات محصولات",
            },
        ),
        migrations.RemoveField(
            model_name="productspecificationvalue",
            name="order",
        ),
        migrations.AddField(
            model_name="specification",
            name="type",
            field=models.CharField(
                choices=[("master", "اصلی"), ("detail", "جزییات")],
                default="master",
                max_length=10,
                verbose_name="نوع خصوصیت",
            ),
        ),
    ]
