# Generated by Django 5.2.1 on 2025-07-26 11:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specification",
            name="category",
        ),
        migrations.CreateModel(
            name="ProductProxy",
            fields=[],
            options={
                "verbose_name": "جدول خصوصیات محصول",
                "verbose_name_plural": "جدول خصوصیات محصول",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="خصوصیات "
            ),
        ),
        migrations.DeleteModel(
            name="ProductSpecificationValue",
        ),
        migrations.DeleteModel(
            name="Specification",
        ),
    ]
