# Generated by Django 5.2.1 on 2025-07-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام شهرستان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "شهرستان",
                "verbose_name_plural": "شهرستان\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام استان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "tel_prefix",
                    models.CharField(max_length=20, verbose_name="پیش شماره استان"),
                ),
            ],
            options={
                "verbose_name": "استان",
                "verbose_name_plural": "استان\u200cها",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام شهر")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="iran.county",
                        verbose_name="شهرستان",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام منطقه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="iran.county",
                        verbose_name="شهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "منطقه",
                "verbose_name_plural": "منطقه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="county",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="iran.province",
                verbose_name="استان",
            ),
        ),
        migrations.CreateModel(
            name="Rural",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام روستا")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rurals",
                        to="iran.county",
                        verbose_name="منطقه",
                    ),
                ),
            ],
            options={
                "verbose_name": "روستا",
                "verbose_name_plural": "روستاها",
            },
        ),
    ]
