# Generated by Django 5.2.1 on 2025-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZarinPal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(max_length=100, verbose_name="Merchant ID"),
                ),
                ("request_url", models.URLField(verbose_name="آدرس درخواست")),
                ("verify_url", models.URLField(verbose_name="آدرس تایید")),
                ("start_pay_url", models.URLField(verbose_name="آدرس شروع پرداخت")),
                ("callback_url", models.URLField(verbose_name="آدرس بازگشت")),
                (
                    "sandbox",
                    models.BooleanField(default=True, verbose_name="آزمایشگاهی"),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=100000, verbose_name="حداقل مبلغ پرداخت"
                    ),
                ),
            ],
            options={
                "verbose_name": "زرین پال",
                "verbose_name_plural": "زرین پال",
            },
        ),
    ]
