# Generated by Django 5.2.1 on 2025-07-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salesman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام فروشنده")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ایمیل فروشنده",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "فروشنده",
                "verbose_name_plural": "فروشنده ها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="نام تامین کننده"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره تلفن ۱",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره تلفن ۲",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="وب سایت"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تامین کننده",
                "verbose_name_plural": "تامین کننده ها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "تلگرام"),
                            ("instagram", "اینستاگرام"),
                            ("facebook", "فیسبوک"),
                            ("youtube", "یوتیوب"),
                            ("whatsapp", "واتس اپ"),
                            ("linkedin", "لینکدین"),
                            ("pinterest", "پینترست"),
                            ("X", "ایکس"),
                        ],
                        max_length=255,
                        verbose_name="پلتفرم",
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس url")),
                (
                    "salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="supplier.salesman",
                        verbose_name="Salesman",
                    ),
                ),
            ],
            options={
                "verbose_name": "شبکه اجتماعی",
                "verbose_name_plural": "شبکه های اجتماعی",
                "ordering": ["platform"],
            },
        ),
        migrations.AddField(
            model_name="salesman",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesmen",
                to="supplier.supplier",
                verbose_name="تامین کننده",
            ),
        ),
    ]
