# Generated by Django 5.2.1 on 2025-07-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0002_pagevisit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagevisit",
            options={
                "ordering": ["-visited_at"],
                "verbose_name": "بازدید صفحه",
                "verbose_name_plural": "بازدیدهای صفحه",
            },
        ),
    ]
