# Generated by Django 5.2.1 on 2025-07-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.BigIntegerField(default=0, verbose_name="مبلغ به ریال"),
                ),
                (
                    "discount",
                    models.BigIntegerField(default=0, verbose_name="تخفیف به ریال"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "پرداخت نشده"),
                            ("paid", "پرداخت شده"),
                            ("pending", "در حال پردازش"),
                            ("delivered", "تحویل داده شده"),
                            ("canceled", "انصراف"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و ساعت ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ و ساعت بروزرسانی "
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "province",
                    models.CharField(
                        default="تهران", max_length=100, verbose_name="استان"
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        default="تهران", max_length=100, verbose_name="شهرستان"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        default="مرکزی", max_length=100, verbose_name="منطقه"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="تهران", max_length=100, verbose_name="شهر"
                    ),
                ),
                (
                    "rural",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="روستا"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد پستی"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                ("price", models.BigIntegerField(default=0, verbose_name="مبلغ")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_products",
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالای سفارش",
                "verbose_name_plural": "کالاهای سفارش",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(default=0, verbose_name="مبلغ ")),
                (
                    "transaction_id",
                    models.CharField(
                        default="111111", max_length=200, verbose_name="شماره تراکنش"
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        default="auth-222222",
                        max_length=200,
                        unique=True,
                        verbose_name="شناسه زرین پال",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "پرداخت شده"), ("failed", "ناموفق")],
                        default="failed",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بروز رسانی"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="order.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت  سفارش",
                "verbose_name_plural": "پرداخت های  سفارش",
            },
        ),
    ]
