# Generated by Django 5.2.1 on 2025-07-06 17:21

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="تلفن"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now=True, max_length=100, verbose_name="زمان ارسال شمسی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تماس های با ما",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="سوال")),
                (
                    "answer",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="پاسخ"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "سوال و جواب",
                "verbose_name_plural": "سوالات و جواب ها",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="عکس"
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری ",
                "verbose_name_plural": "گالری ",
            },
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="نام")),
                ("url", models.URLField(verbose_name="لینک")),
                (
                    "type",
                    models.CharField(
                        choices=[("internal", "داخلی"), ("external", "خارجی")],
                        default="Internal",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک",
                "verbose_name_plural": "لینک ها",
            },
        ),
        migrations.CreateModel(
            name="MailProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="نام ارائه دهنده ایمیل"
                    ),
                ),
                (
                    "smtp_sender_email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل فرستنده ایمیل  ",
                    ),
                ),
                (
                    "smtp_sender_password",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="رمز عبور ایمیل",
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="سرور ایمیل",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True, default=None, null=True, verbose_name="پورت ایمیل"
                    ),
                ),
            ],
            options={
                "verbose_name": "ارائه دهنده ایمیل",
                "verbose_name_plural": "ارائه دهندگان ایمیل",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name=" نام ")),
                ("url", models.CharField(blank=True, null=True, verbose_name="لینک")),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "منو",
                "verbose_name_plural": "منوها",
            },
        ),
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام وبسایت")),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="شعار"
                    ),
                ),
                (
                    "logo_header",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="website",
                        verbose_name="لوگوسربرگ",
                    ),
                ),
                (
                    "logo_footer",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="website",
                        verbose_name="لوگو فوتر",
                    ),
                ),
                ("email1", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "email2",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="آدرس ")),
                ("telephone1", models.CharField(max_length=20, verbose_name=" تلفن ")),
                (
                    "telephone2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name=" تلفن "
                    ),
                ),
                (
                    "copyright",
                    models.CharField(max_length=200, verbose_name=" کپی رایت "),
                ),
                (
                    "copyright_link",
                    models.URLField(
                        default="https://wedosoft.ir", verbose_name="لینک کپی رایت"
                    ),
                ),
                ("map_url", models.URLField(verbose_name="آدرس گوگل مپ")),
                (
                    "enamad_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="شماره نماد"
                    ),
                ),
                (
                    "enamad_tag",
                    models.TextField(blank=True, null=True, verbose_name="تگ نماد"),
                ),
                (
                    "working_hours",
                    models.TextField(blank=True, null=True, verbose_name="ساعات کاری"),
                ),
                (
                    "instagram_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="آیدی اینستاگرام",
                    ),
                ),
                (
                    "is_selling",
                    models.BooleanField(default=True, verbose_name="فروش فعال"),
                ),
            ],
            options={
                "verbose_name": "اطلاعات وبسایت",
                "verbose_name_plural": "اطلاعات وبسایت",
            },
        ),
        migrations.CreateModel(
            name="SMSProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="نام ارائه دهنده پیامک"
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="آدرس ای پی آی ارسال پیامک",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="نام کاربری پیامک",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="رمز عبور پیامک",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="شماره ارسال کننده پیامک",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارائه دهنده پیامک",
                "verbose_name_plural": "ارائه دهندگان پیامک",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("telegram", "تلگرام"),
                            ("instagram", "اینستاگرام"),
                            ("facebook", "فیسبوک"),
                            ("youtube", "یوتیوب"),
                            ("whatsapp", "واتس اپ"),
                            ("linkedin", "لینکدین"),
                            ("pinterest", "پینترست"),
                            ("X", "ایکس"),
                        ],
                        default="telegram",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "شبکه اجتماعی کاربران",
                "verbose_name_plural": "شبکه های اجتماعی کاربران",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "message",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="پیام"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "تجربه مشتری",
                "verbose_name_plural": "تجربیات مشتریان",
            },
        ),
        migrations.CreateModel(
            name="SubMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name=" نام ")),
                ("url", models.CharField(blank=True, null=True, verbose_name="لینک")),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submenus",
                        to="siteInfo.menu",
                        verbose_name="منو",
                    ),
                ),
            ],
            options={
                "verbose_name": "زیر منو",
                "verbose_name_plural": "زیر منوها",
            },
        ),
    ]
