# Generated by Django 5.2.1 on 2025-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteInfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="sell_mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="موبایل فروشنده"
            ),
        ),
        migrations.AlterField(
            model_name="siteinfo",
            name="telephone1",
            field=models.CharField(max_length=20, verbose_name=" تلفن 1"),
        ),
        migrations.AlterField(
            model_name="siteinfo",
            name="telephone2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name=" تلفن 2"
            ),
        ),
    ]
