# Generated by Django 5.2.1 on 2025-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteInfo", "0002_siteinfo_sell_mobile_alter_siteinfo_telephone1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="map_url",
            field=models.URLField(max_length=1000, verbose_name="آدرس گوگل مپ"),
        ),
    ]
